import type { EditorState } from "@/domains/canvas/public";

export type CanvasInteractionModel = Pick<EditorState,
  | "tool"
  | "canvasMode"
  | "brushChar"
  | "brushColor"
  | "setBrushColor"
  | "canvasColorPickerTarget"
  | "setCanvasColorPickerTarget"
  | "setOffset"
  | "setZoom"
  | "addScratchPoints"
  | "commitScratch"
  | "commitStructuredShape"
  | "setTextCursor"
  | "addSelection"
  | "clearSelections"
  | "clearInteractionState"
  | "erasePoints"
  | "offset"
  | "zoom"
  | "grid"
  | "updateScratchForShape"
  | "setHoveredGrid"
  | "fillArea"
  | "canvasBounds"
  | "structuredScene"
  | "editingStructuredTextNodeId"
  | "selectedStructuredNodeIds"
  | "setStructuredGridFocus"
  | "setStructuredContextPoint"
  | "setSelectedStructuredNodeIds"
  | "setSelectedStructuredSplitHandle"
  | "setEditingStructuredTextNodeId"
  | "setStructuredTextSelection"
  | "structuredTextSelection"
  | "setStructuredTextColor"
  | "applyStructuredScene"
  | "updateStructuredNode"
>;

export type CanvasRenderModel = Pick<EditorState,
  | "offset"
  | "zoom"
  | "grid"
  | "scratchLayer"
  | "textCursor"
  | "selections"
  | "staticGridSelection"
  | "staticGridEditMode"
  | "showGrid"
  | "hoveredGrid"
  | "tool"
  | "canvasMode"
  | "canvasBounds"
  | "animationTimeline"
  | "animationPlaybackFrameId"
  | "structuredScene"
  | "selectedStructuredNodeIds"
  | "selectedStructuredBoxId"
  | "structuredContextPoint"
  | "structuredGridFocus"
  | "editingStructuredTextNodeId"
  | "structuredTextSelection"
  | "canvasColorPickerTarget"
>;

export type CanvasEditorModel = Pick<EditorState,
  | "textCursor"
  | "staticGridSelection"
  | "staticGridEditMode"
  | "writeTextString"
  | "backspaceText"
  | "deleteTextForward"
  | "newlineText"
  | "indentText"
  | "moveTextCursor"
  | "moveStaticGridFocus"
  | "moveStructuredGridFocus"
  | "setTextCursor"
  | "selections"
  | "offset"
  | "zoom"
  | "setOffset"
  | "moveSelections"
  | "expandSelection"
  | "fillSelectionsWithChar"
  | "clearSelections"
  | "structuredGridFocus"
  | "setStructuredGridFocus"
  | "selectedStructuredNodeIds"
  | "setSelectedStructuredNodeIds"
  | "setSelectedStructuredSplitHandle"
  | "setEditingStructuredTextNodeId"
  | "setStructuredTextSelection"
  | "structuredScene"
  | "structuredComponents"
  | "brushColor"
  | "canvasColorPickerTarget"
  | "setCanvasColorPickerTarget"
  | "setHoveredGrid"
  | "getNextStructuredOrder"
  | "applyStructuredScene"
  | "setStructuredContextPoint"
  | "activeCanvasHasSavedViewport"
>;
