import { useEditorStore } from "@/domains/canvas/public";
import { useShallow } from "zustand/react/shallow";

export const useAsciiCanvasModels = () => {
  const interactionStore = useEditorStore(
    useShallow((state) => ({
      tool: state.tool,
      canvasMode: state.canvasMode,
      brushChar: state.brushChar,
      brushColor: state.brushColor,
      setBrushColor: state.setBrushColor,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
      setCanvasColorPickerTarget: state.setCanvasColorPickerTarget,
      setOffset: state.setOffset,
      setZoom: state.setZoom,
      addScratchPoints: state.addScratchPoints,
      commitScratch: state.commitScratch,
      commitStructuredShape: state.commitStructuredShape,
      setTextCursor: state.setTextCursor,
      addSelection: state.addSelection,
      clearSelections: state.clearSelections,
      clearInteractionState: state.clearInteractionState,
      erasePoints: state.erasePoints,
      offset: state.offset,
      zoom: state.zoom,
      grid: state.grid,
      updateScratchForShape: state.updateScratchForShape,
      setHoveredGrid: state.setHoveredGrid,
      fillArea: state.fillArea,
      structuredScene: state.structuredScene,
      editingStructuredTextNodeId: state.editingStructuredTextNodeId,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      setStructuredGridFocus: state.setStructuredGridFocus,
      setStructuredContextPoint: state.setStructuredContextPoint,
      setSelectedStructuredNodeIds: state.setSelectedStructuredNodeIds,
      setSelectedStructuredSplitHandle: state.setSelectedStructuredSplitHandle,
      setEditingStructuredTextNodeId: state.setEditingStructuredTextNodeId,
      setStructuredTextSelection: state.setStructuredTextSelection,
      structuredTextSelection: state.structuredTextSelection,
      setStructuredTextColor: state.setStructuredTextColor,
      applyStructuredScene: state.applyStructuredScene,
      updateStructuredNode: state.updateStructuredNode,
    }))
  );
  const rendererStore = useEditorStore(
    useShallow((state) => ({
      offset: state.offset,
      zoom: state.zoom,
      grid: state.grid,
      scratchLayer: state.scratchLayer,
      textCursor: state.textCursor,
      selections: state.selections,
      staticGridSelection: state.staticGridSelection,
      staticGridEditMode: state.staticGridEditMode,
      showGrid: state.showGrid,
      hoveredGrid: state.hoveredGrid,
      tool: state.tool,
      canvasMode: state.canvasMode,
      structuredScene: state.structuredScene,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      selectedStructuredBoxId: state.selectedStructuredBoxId,
      structuredContextPoint: state.structuredContextPoint,
      structuredGridFocus: state.structuredGridFocus,
      editingStructuredTextNodeId: state.editingStructuredTextNodeId,
      structuredTextSelection: state.structuredTextSelection,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
    }))
  );
  const editorStore = useEditorStore(
    useShallow((state) => ({
      textCursor: state.textCursor,
      staticGridSelection: state.staticGridSelection,
      staticGridEditMode: state.staticGridEditMode,
      writeTextString: state.writeTextString,
      backspaceText: state.backspaceText,
      deleteTextForward: state.deleteTextForward,
      newlineText: state.newlineText,
      indentText: state.indentText,
      moveTextCursor: state.moveTextCursor,
      moveStaticGridFocus: state.moveStaticGridFocus,
      moveStructuredGridFocus: state.moveStructuredGridFocus,
      setTextCursor: state.setTextCursor,
      selections: state.selections,
      offset: state.offset,
      zoom: state.zoom,
      setOffset: state.setOffset,
      moveSelections: state.moveSelections,
      expandSelection: state.expandSelection,
      fillSelectionsWithChar: state.fillSelectionsWithChar,
      clearSelections: state.clearSelections,
      structuredGridFocus: state.structuredGridFocus,
      setStructuredGridFocus: state.setStructuredGridFocus,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      setSelectedStructuredNodeIds: state.setSelectedStructuredNodeIds,
      setSelectedStructuredSplitHandle: state.setSelectedStructuredSplitHandle,
      setEditingStructuredTextNodeId: state.setEditingStructuredTextNodeId,
      setStructuredTextSelection: state.setStructuredTextSelection,
      structuredScene: state.structuredScene,
      structuredComponents: state.structuredComponents,
      brushColor: state.brushColor,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
      setCanvasColorPickerTarget: state.setCanvasColorPickerTarget,
      setHoveredGrid: state.setHoveredGrid,
      getNextStructuredOrder: state.getNextStructuredOrder,
      applyStructuredScene: state.applyStructuredScene,
      setStructuredContextPoint: state.setStructuredContextPoint,
      activeCanvasHasSavedViewport: state.activeCanvasHasSavedViewport,
    }))
  );

  return {
    interaction: interactionStore,
    renderer: rendererStore,
    editor: editorStore,
  };
};

