import { useCanvasRuntime, useCanvasState } from "@/domains/canvas/public";
import { useShallow } from "zustand/react/shallow";

export const useCanvasEditorModels = () => {
  const { commands: canvasCommands, queries: canvasQueries } = useCanvasRuntime();
  const interactionState = useCanvasState(
    useShallow((state) => ({
      activeCanvasId: state.activeCanvasId,
      tool: state.tool,
      canvasMode: state.canvasMode,
      slideDeck: state.slideDeck,
      brushChar: state.brushChar,
      brushColor: state.brushColor,
      brushBackgroundColor: state.brushBackgroundColor,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
      offset: state.offset,
      zoom: state.zoom,
      grid: state.grid,
      staticGridSelection: state.staticGridSelection,
      structuredScene: state.structuredScene,
      editingStructuredTextNodeId: state.editingStructuredTextNodeId,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      structuredTextSelection: state.structuredTextSelection,
    }))
  );
  const interactionStore = {
    ...interactionState,
    setBrushColor: canvasCommands.preferences.setBrushColor,
    setBrushBackgroundColor: canvasCommands.preferences.setBrushBackgroundColor,
    setCanvasColorPickerTarget: canvasCommands.interaction.setColorPickerTarget,
    setOffset: canvasCommands.viewport.setOffset,
    setZoom: canvasCommands.viewport.setZoom,
    setViewport: canvasCommands.viewport.setViewport,
    addScratchPoints: canvasCommands.grid.addScratchPoints,
    commitScratch: canvasCommands.grid.commitScratch,
    commitStructuredShape: canvasCommands.structured.commitShape,
    setTextCursor: canvasCommands.interaction.setTextCursor,
    setStaticGridActiveCell: canvasCommands.staticGrid.setActiveCell,
    addSelection: canvasCommands.selection.add,
    clearSelections: canvasCommands.selection.clear,
    clearInteractionState: canvasCommands.selection.clearInteraction,
    erasePoints: canvasCommands.grid.erasePoints,
    updateScratchForShape: canvasCommands.grid.updateScratchForShape,
    setHoveredGrid: canvasCommands.interaction.setHoveredGrid,
    fillArea: canvasCommands.grid.fillArea,
    setStructuredGridFocus: canvasCommands.interaction.setStructuredGridFocus,
    setStructuredContextPoint: canvasCommands.interaction.setStructuredContextPoint,
    setSelectedStructuredNodeIds: canvasCommands.interaction.setSelectedStructuredNodeIds,
    setSelectedStructuredSplitHandle: canvasCommands.interaction.setSelectedStructuredSplitHandle,
    setEditingStructuredTextNodeId: canvasCommands.interaction.setEditingStructuredTextNodeId,
    setStructuredTextSelection: canvasCommands.interaction.setStructuredTextSelection,
    setStructuredTextColor: canvasCommands.structured.setTextColor,
    applyStructuredScene: canvasCommands.structured.applyScene,
    updateStructuredNode: canvasCommands.structured.updateNode,
  };
  const rendererStore = useCanvasState(
    useShallow((state) => ({
      offset: state.offset,
      zoom: state.zoom,
      grid: state.grid,
      scratchLayer: state.scratchLayer,
      textCursor: state.textCursor,
      selections: state.selections,
      staticGridSelection: state.staticGridSelection,
      staticGridEditMode: state.staticGridEditMode,
      showGrid: state.showGrid,
      hoveredGrid: state.hoveredGrid,
      tool: state.tool,
      canvasMode: state.canvasMode,
      slideDeck: state.slideDeck,
      structuredScene: state.structuredScene,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      selectedStructuredBoxId: state.selectedStructuredBoxId,
      structuredContextPoint: state.structuredContextPoint,
      structuredGridFocus: state.structuredGridFocus,
      editingStructuredTextNodeId: state.editingStructuredTextNodeId,
      structuredTextSelection: state.structuredTextSelection,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
    }))
  );
  const editorState = useCanvasState(
    useShallow((state) => ({
      textCursor: state.textCursor,
      staticGridSelection: state.staticGridSelection,
      staticGridEditMode: state.staticGridEditMode,
      selections: state.selections,
      offset: state.offset,
      zoom: state.zoom,
      structuredGridFocus: state.structuredGridFocus,
      selectedStructuredNodeIds: state.selectedStructuredNodeIds,
      structuredScene: state.structuredScene,
      structuredComponents: state.structuredComponents,
      brushColor: state.brushColor,
      canvasColorPickerTarget: state.canvasColorPickerTarget,
      activeCanvasHasSavedViewport: state.activeCanvasHasSavedViewport,
    }))
  );
  const editorStore = {
    ...editorState,
    writeTextString: canvasCommands.text.write,
    backspaceText: canvasCommands.text.backspace,
    deleteTextForward: canvasCommands.text.deleteForward,
    newlineText: canvasCommands.text.newline,
    indentText: canvasCommands.text.indent,
    moveTextCursor: canvasCommands.text.moveCursor,
    moveStaticGridFocus: canvasCommands.staticGrid.moveFocus,
    moveStaticGridFocusToEdge: canvasCommands.staticGrid.moveFocusToEdge,
    moveStaticGridFocusToContentBoundary:
      canvasCommands.staticGrid.moveFocusToContentBoundary,
    selectStaticGridAll: canvasCommands.staticGrid.selectAll,
    selectStaticGridRow: canvasCommands.staticGrid.selectRow,
    selectStaticGridColumn: canvasCommands.staticGrid.selectColumn,
    enterStaticGridTextEdit: canvasCommands.staticGrid.enterTextEdit,
    exitStaticGridTextEdit: canvasCommands.staticGrid.exitTextEdit,
    moveStructuredGridFocus: canvasCommands.interaction.moveStructuredGridFocus,
    setTextCursor: canvasCommands.interaction.setTextCursor,
    setOffset: canvasCommands.viewport.setOffset,
    moveSelections: canvasCommands.selection.move,
    expandSelection: canvasCommands.selection.expand,
    fillSelectionsWithChar: canvasCommands.selection.fillWithChar,
    clearSelections: canvasCommands.selection.clear,
    setStructuredGridFocus: canvasCommands.interaction.setStructuredGridFocus,
    setSelectedStructuredNodeIds: canvasCommands.interaction.setSelectedStructuredNodeIds,
    setSelectedStructuredSplitHandle: canvasCommands.interaction.setSelectedStructuredSplitHandle,
    setEditingStructuredTextNodeId: canvasCommands.interaction.setEditingStructuredTextNodeId,
    setStructuredTextSelection: canvasCommands.interaction.setStructuredTextSelection,
    setCanvasColorPickerTarget: canvasCommands.interaction.setColorPickerTarget,
    setHoveredGrid: canvasCommands.interaction.setHoveredGrid,
    getNextStructuredOrder: canvasQueries.getNextStructuredOrder,
    applyStructuredScene: canvasCommands.structured.applyScene,
    setStructuredContextPoint: canvasCommands.interaction.setStructuredContextPoint,
  };

  return {
    interaction: interactionStore,
    renderer: rendererStore,
    editor: editorStore,
  };
};
