export type {
  GridAddress,
  GridBounds,
  GridEdge,
  GridEditMode,
  GridRange,
  GridSelectionState,
} from "./model/static-grid";
export {
  collapseGridSelectionTo,
  clampGridAddressToBounds,
  createGridSelectionState,
  createStaticGridState,
  extendGridSelectionTo,
  getConnectedGridRange,
  getEffectiveGridBounds,
  getStaticGridSelectionAreas,
  getStaticGridViewState,
  gridRangeFromSelectionArea,
  gridRangesEqual,
  moveGridAddress,
  moveGridAddressToContentBoundary,
  moveGridAddressToEdge,
  normalizeGridRange,
  resolveGridFillRange,
  selectionAreaFromGridRange,
  selectionAreasFromGridRanges,
  selectGridColumn,
  selectGridRange,
  selectGridRow,
  syncGridSelectionFromLegacy,
} from "./model/static-grid";
