import type { StructuredComponentDefinition } from "../components/types";

export const FILETREE_TEMPLATE: StructuredComponentDefinition = {
  id: "filetree",
  label: "File tree",
  build: ({ createLine, createText }) => [
    createLine(15, 0, { x: 0, y: 1 }, { color: "#64748b" }, "rootGuide", "vertical"),
    createLine(10, 1, { x: 2, y: 3 }, { color: "#64748b" }, "srcGuide", "vertical"),
    createLine(2, 2, { x: 4, y: 4 }, { color: "#64748b" }, "appGuide", "vertical"),
    createLine(4, 3, { x: 4, y: 7 }, { color: "#64748b" }, "componentsGuide", "vertical"),
    createLine(1, 4, { x: 4, y: 12 }, { color: "#64748b" }, "libGuide", "vertical"),
    createLine(1, 5, { x: 6, y: 8 }, { color: "#64748b" }, "uiGuide", "vertical"),
    createText(" PROJECT-ROOT", { x: 0, y: 0 }, 10, undefined, undefined, "root"),
    createText("󰉋 node_modules", { x: 3, y: 1 }, 11, undefined, undefined, "folder"),
    createText(" src", { x: 2, y: 2 }, 12, undefined, undefined, "folder"),
    createText(" app", { x: 4, y: 3 }, 13, undefined, undefined, "folder"),
    createText(" layout.tsx", { x: 6, y: 4 }, 14, undefined, undefined, "file"),
    createText(" page.tsx", { x: 6, y: 5 }, 15, undefined, undefined, "file"),
    createText(" components", { x: 4, y: 6 }, 16, undefined, undefined, "folder"),
    createText(" ui", { x: 6, y: 7 }, 17, undefined, undefined, "folder"),
    createText(" button.tsx", { x: 8, y: 8 }, 18, undefined, undefined, "file"),
    createText(" footer.tsx", { x: 6, y: 9 }, 19, undefined, undefined, "file"),
    createText(" header.tsx", { x: 6, y: 10 }, 20, undefined, undefined, "file"),
    createText(" lib", { x: 4, y: 11 }, 21, undefined, undefined, "folder"),
    createText(" utils.ts", { x: 6, y: 12 }, 22, undefined, undefined, "file"),
    createText("󰉋 public", { x: 3, y: 13 }, 23, undefined, undefined, "folder"),
    createText("󰘦 package.json", { x: 3, y: 14 }, 24, undefined, undefined, "file"),
    createText(" README.md", { x: 3, y: 15 }, 25, undefined, undefined, "file"),
  ],
};
