export const BLOCK_LAYOUT_DASHBOARD_SOURCE = [
  '╭────────────────────────────╮',
  '│ [1;38;2;91;95;199mCharDesk Workspace[0m         │',
  '│ Spatial text, shared canvas│',
  '│ [38;2;34;197;94m● Live[0m · 12 collaborators  │',
  '╰────────────────────────────╯',
  '|||',
  '╭──────────────────────╮',
  '│ Runtime              │',
  '│ Canvases          12 │',
  '│ Blocks           248 │',
  '│ Sync          18 ms  │',
  '╰──────────────────────╯',
  '|||',
  'Languages',
  'English    Ready',
  '中文       就绪',
  '日本語     準備完了',
  '한국어     준비 완료',
  'Emoji      👋 🚀',
  '---',
  '[1mInput · canvas.json[0m',
  '```json',
  '{',
  '  "canvas": "launch-plan",',
  '  "owner": "Ada",',
  '  "locale": "zh-CN",',
  '  "nodes": 42',
  '}',
  '```',
  '|||',
  '╭────────────────────────╮',
  '│ Transform pipeline     │',
  '│                        │',
  '│ Markdown               │',
  '│    ↓ parse             │',
  '│ CharGraph              │',
  '│    ↓ layout            │',
  '│ Unicode Canvas         │',
  '╰────────────────────────╯',
  '|||',
  '[1mOutput · scene[0m',
  'launch-plan',
  '├─ brief',
  '│  ├─ goals',
  '│  └─ audience',
  '├─ storyboard',
  '│  ├─ intro',
  '│  └─ demo',
  '└─ publish ✓',
  '---',
  '╭──────────────────────────────╮',
  '│ Recent activity              │',
  '│                              │',
  '│ 10:42  Ada edited brief      │',
  '│ 10:39  Lin added palette     │',
  '│ 10:31  Yuki linked CharGraph │',
  '│ 10:24  민준 resolved comment │',
  '╰──────────────────────────────╯',
  '|||',
  '[1mPalette[0m',
  '[38;2;239;68;68m● Coral[0m    #ef4444',
  '[38;2;245;158;11m● Amber[0m    #f59e0b',
  '[38;2;34;197;94m● Green[0m    #22c55e',
  '[38;2;59;130;246m● Blue[0m     #3b82f6',
  '[38;2;139;92;246m● Violet[0m   #8b5cf6',
  '|||',
  '[1mLayout notes[0m',
  '|||  next field',
  '---  next row',
  '',
  'Escaped literals',
  '\\|||',
  '\\---',
  '---',
  '╭────────────────────────────────────────────────────────────╮',
  '│ [1mOpen source workspace[0m                                      │',
  '│ CharDesk · ]8;;https://github.com/Sayhi-bzb/CharDesk\\[4;38;2;37;99;235mgithub.com/Sayhi-bzb/CharDesk[0m]8;;\\                   │',
  '│ CharGraph · ]8;;https://chardesk.com/chargraph/\\[4;38;2;37;99;235mchardesk.com/chargraph[0m]8;;\\                         │',
  '│ [38;2;34;197;94mAll systems operational[0m · shared example                   │',
  '╰────────────────────────────────────────────────────────────╯',
].join('\n');
